# Generated by Django 3.1.2 on 2021-04-22 08:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavCharacter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('character_id', models.CharField(max_length=255)),
                ('character_name', models.CharField(max_length=255)),
                ('character_gender', models.CharField(max_length=255)),
                ('character_race', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_id', models.CharField(max_length=255)),
                ('quote_dialog', models.CharField(max_length=255)),
                ('character_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspireapp.favcharacter')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspireapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='favcharacter',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspireapp.user'),
        ),
    ]
